Repository Mrinank-Bhowmick/python-beginner-projects, pull requests merged in 2023-10, with the labels that each got.

#362 Adding is_empty() and print_csv() funtions to project.
  projects/Expense-Tracker/main.py
Labels: hacktoberfest, hacktoberfest-accepted

#368 Add: Type Racer Game
  projects/Type Racer Game/type_racer.py
Labels: hacktoberfest, hacktoberfest-23, hacktoberfest-accepted

#395 Add: Tile Master Game
  projects/Tile Matching/tile_matching.py
Labels: hacktoberfest, hacktoberfest-accepted

#535 Adding requirements.txt and documentation for NASA APOD
  projects/NASA-APOD/README.md
  projects/NASA-APOD/requirements.txt
Labels: hacktoberfest-accepted

#451 Update Twitter-RT-Bot.py
  projects/Twitter-Bot/Twitter-RT-Bot.py
Labels: hacktoberfest-accepted

#442 Create joke_provider.py
  projects/joke_provider.py
Labels: hacktoberfest-accepted

#435 Ehancenments for Image Compressor App
  projects/Image compressor/imagecompressor.py
Labels: hacktoberfest-accepted

#434 Added more features to text-translate
  projects/text-translate/main.py
Labels: hacktoberfest-accepted

#432 Add age calculater project
  README.md
  projects/Calculate Age/README.md
  projects/Calculate Age/calculate.py
Labels: hacktoberfest-accepted

#431 Snake_water_gun
  projects/snake_water_gun_game/Snake_Water_Gun_Game.py
Labels: hacktoberfest-accepted

#428 Image to text added
  projects/Image to text generation project/Image_to_text_generation.ipynb
Labels: hacktoberfest-accepted

#423 Python story generator updated with some addition features
  projects/Python story generator/story.py
Labels: hacktoberfest-accepted

#419 sponge-bob in python using turtle
  projects/sponge-bob/main.py
Labels: hacktoberfest-accepted

#421 Lawyer AI Assistant Project #321
  projects/Lawyer AI Assistant/Lawyer_AI_Assistant_Project.ipynb
Labels: hacktoberfest-accepted

#410 Create Poker-hands-sim.py
  projects/Poker-hands-sim.py
Labels: hacktoberfest-accepted

#405 Create tetrisGame.py
  projects/Tetris Game/tetrisGame.py
Labels: hacktoberfest-accepted

#404 Adding Analog Clock Project
  projects/Analog Clock/analog_clock.py
  projects/AnalogClock/analog_clock
Labels: hacktoberfest-accepted

#411 Ayush18
  projects/Conway’s-Game-Of-Life.py
  projects/conwaygame.py
Labels: hacktoberfest-accepted

#355 Added Docstrings to functions and libraries.
  projects/Calculator/main.py
Labels: hacktoberfest-accepted

#401 Add battleship cli game
  projects/Battleship/README.md
  projects/Battleship/main.py
Labels: hacktoberfest-accepted

#487 Added-Simple-Plagiarism-Checker-Project
  projects/Simple-Plagiarism-Checker-Project/README.md
  projects/Simple-Plagiarism-Checker-Project/plag.py
  projects/Simple-Plagiarism-Checker-Project/req.txt
  projects/Simple-Plagiarism-Checker-Project/templates/index.html
Labels: hacktoberfest, hacktoberfest-accepted
